
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chris Etienne # Name of website
email: cetienn01@gmail.com
name: "http://chrisetienne.com"
description: >- # this means to ignore newlines until "baseurl:" # Short description of your site
  Welcome to my mysterious world
author: Chris Etienne
meta_author: Etienne Chris
baseurl: "/" # the subpath of your site, e.g. /blog
url: " "
baseurlknitr: "/"
about:
  I can be found at the bench, conducting experiments,
  as well as in the computation side, performing bioinformatics analyses
skills: "bioinformatics - immuno-oncology - molecular biology"
avatar: /static/images/me.jpg

# --- Background colour/image options --- #
# Personalize the colors in your website. Colour values can be any valid CSS colour
background-image: '/science-stock-image.png/'
image:
  background: '/science-stock-image.png/'
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour
navbar-img: '/Desktop/science-stock-image.png/'
#footer-img: "/img/bgimage.png"
#page-img: "/img/bgimage.png"

# --- Navigation bar options --- #
# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources: "resources"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  hard_wrap: false
highlighter: rouge
paginate: 5
paginate_path: "/posts/page:num/"

remote_theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-coffeescript

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
#permalink: pretty
# Number of news stories on the front page.
front_page_news: 3

#Social Profiles / Links
# share:
twitter_username: cetienn01
linkedin_username: christian-etienne
github_username:  cetienn01
medium_username: cetienn01

# Social Media
twitter: true
linkedin: true
github:
  repo: https://github.com/cetienn01/cetienn01.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cetienn01
  - title: github
    url: http://github.com/cetienn01

# Postal address (add as many lines as necessary)
address:
  - line: 3 Forbes Rd.
  - line: Lexington, MA 02421
# Base pathname for links.
base: '/chrisetienne.com'
base: ''
github_button_location_page_bottom: true

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - tile: About Me
      link: /aboutme.html
    - title: Research
      link: /research.html
    - title: Publications
      link: /publications.html
    - title: Projects
      link: /projects.html
    - title: CV
      link: /cv/cv.pdf
